# config.yaml

program: train.py
method: random
metric:
 name: val_loss
 goal: minimize
parameters:
 learning_rate:
   min: 0.001
   max: 0.01
 optimizer:
   values: ["adam", "sgd"]
 epochs:
   value: 10
 batch_size:
   value: 128